services:
  frontend:
    build:
      context: ./es-3-fe
      dockerfile: Dockerfile
      args:
        VITE_BASE_PATH: http://localhost:4000/api/v1
    ports:
      - "3000:3000"
    networks:
      - internal

  backend:
    build:
      context: ./es-3-backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - internal

networks:
  internal:
    driver: bridge